pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "./outputs/flower"

train_data:
  video_root: "./training_data/flower_in_bloom"
  # prompt: "a man is skiing"
  n_sample_frames: 4
  width: 512
  height: 320
  sample_start_idx: 0
  sample_frame_rate: 2

validation_data:
  image_path: "./benchmark/flower_in_bloom"
  prompts:
    - "a flower in bloom"
    - "a red flower in bloom"
    - "a pink flower blooms"
    - "a red flower blooms"

  video_length: 4
  width: 512
  height: 320
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: True
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 3
checkpointing_steps: 50000
validation_steps: 2
trainable_modules:
  - "conv1d"
  - "attn1.to_q"
  - "conv_gate"
  - "attn_temp"
  - "self_attention"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
