pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "./outputs/demo_helicopter"

train_data:
  video_root: "./training_data/helicopter"
  # prompt: "a man is skiing"
  n_sample_frames: 4
  width: 512
  height: 320
  sample_start_idx: 0
  sample_frame_rate: 1

validation_data:
  image_path: "benchmark/helicopter"
  prompts:
    - "a helicopter over the sea"
    - "a LEGO helicopter flies in the sky"
  video_length: 4
  width: 512
  height: 320
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: False
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 4
checkpointing_steps: 150000
validation_steps: 2
trainable_modules:
  - "conv1d"
  - "attn1.to_q"
  - "conv_gate"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
